version: "3.9"
services:
  alloc:
    build:
      context: .
      dockerfile: containers/alloc/Containerfile
    volumes:
      - .:/var/www/html:z
    ports:
      - 4000:80
    extra_hosts:
      - "host.docker.internal:127.0.0.1"
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes
    links:
      - database:database
    depends_on:
      - "database"
  database:
    build:
      context: .
      dockerfile: containers/database/Containerfile
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  database_data:
