version: "3.9"
services:
  alloc:
    build:
      context: .
      dockerfile: docker/alloc/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 4000:80
    links:
      - database:database
    depends_on:
      - "database"
  database:
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  database_data:
